#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'spec.pb'; rescue LoadError; end

module Main
  # forward declarations
  class GetProjectRootRequest < ::ProtocolBuffers::Message; end
  class GetProjectRootResponse < ::ProtocolBuffers::Message; end
  class GetAllStepsRequest < ::ProtocolBuffers::Message; end
  class GetAllStepsResponse < ::ProtocolBuffers::Message; end
  class GetAllSpecsRequest < ::ProtocolBuffers::Message; end
  class GetAllSpecsResponse < ::ProtocolBuffers::Message; end
  class GetStepValueRequest < ::ProtocolBuffers::Message; end
  class GetStepValueResponse < ::ProtocolBuffers::Message; end
  class ErrorResponse < ::ProtocolBuffers::Message; end
  class APIMessage < ::ProtocolBuffers::Message; end

  class GetProjectRootRequest < ::ProtocolBuffers::Message
    set_fully_qualified_name "main.GetProjectRootRequest"

  end

  class GetProjectRootResponse < ::ProtocolBuffers::Message
    set_fully_qualified_name "main.GetProjectRootResponse"

    required :string, :projectRoot, 1
  end

  class GetAllStepsRequest < ::ProtocolBuffers::Message
    set_fully_qualified_name "main.GetAllStepsRequest"

  end

  class GetAllStepsResponse < ::ProtocolBuffers::Message
    set_fully_qualified_name "main.GetAllStepsResponse"

    repeated :string, :steps, 1
  end

  class GetAllSpecsRequest < ::ProtocolBuffers::Message
    set_fully_qualified_name "main.GetAllSpecsRequest"

  end

  class GetAllSpecsResponse < ::ProtocolBuffers::Message
    set_fully_qualified_name "main.GetAllSpecsResponse"

    repeated ::Main::ProtoSpec, :specs, 1
  end

  class GetStepValueRequest < ::ProtocolBuffers::Message
    set_fully_qualified_name "main.GetStepValueRequest"

    required :string, :stepText, 1
  end

  class GetStepValueResponse < ::ProtocolBuffers::Message
    set_fully_qualified_name "main.GetStepValueResponse"

    required :string, :stepValue, 1
    repeated :string, :parameters, 2
  end

  class ErrorResponse < ::ProtocolBuffers::Message
    set_fully_qualified_name "main.ErrorResponse"

    required :string, :error, 1
  end

  class APIMessage < ::ProtocolBuffers::Message
    # forward declarations

    # enums
    module APIMessageType
      include ::ProtocolBuffers::Enum

      set_fully_qualified_name "main.APIMessage.APIMessageType"

      GetProjectRootRequest = 1
      GetProjectRootResponse = 2
      GetAllStepsRequest = 3
      GetAllStepResponse = 4
      GetAllSpecsRequest = 5
      GetAllSpecsResponse = 6
      GetStepValueRequest = 7
      GetStepValueResponse = 8
      ErrorResponse = 9
    end

    set_fully_qualified_name "main.APIMessage"

    required ::Main::APIMessage::APIMessageType, :messageType, 1
    required :int64, :messageId, 2
    optional ::Main::GetProjectRootRequest, :projectRootRequest, 3
    optional ::Main::GetProjectRootResponse, :projectRootResponse, 4
    optional ::Main::GetAllStepsRequest, :allStepsRequest, 5
    optional ::Main::GetAllStepsResponse, :allStepsResponse, 6
    optional ::Main::GetAllSpecsRequest, :allSpecsRequest, 7
    optional ::Main::GetAllSpecsResponse, :allSpecsResponse, 8
    optional ::Main::GetStepValueRequest, :stepValueRequest, 9
    optional ::Main::GetStepValueResponse, :stepValueResponse, 10
    optional ::Main::ErrorResponse, :error, 11
  end

end
