# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

require 'google/protobuf'

require 'spec_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("api.proto", :syntax => :proto3) do
    add_message "gauge.messages.GetProjectRootRequest" do
    end
    add_message "gauge.messages.GetProjectRootResponse" do
      optional :projectRoot, :string, 1
    end
    add_message "gauge.messages.GetInstallationRootRequest" do
    end
    add_message "gauge.messages.GetInstallationRootResponse" do
      optional :installationRoot, :string, 1
    end
    add_message "gauge.messages.GetAllStepsRequest" do
    end
    add_message "gauge.messages.GetAllStepsResponse" do
      repeated :allSteps, :message, 1, "gauge.messages.ProtoStepValue"
    end
    add_message "gauge.messages.SpecsRequest" do
      repeated :specs, :string, 1
    end
    add_message "gauge.messages.SpecsResponse" do
      repeated :details, :message, 1, "gauge.messages.SpecsResponse.SpecDetail"
    end
    add_message "gauge.messages.SpecsResponse.SpecDetail" do
      optional :spec, :message, 1, "gauge.messages.ProtoSpec"
      repeated :parseErrors, :message, 2, "gauge.messages.Error"
    end
    add_message "gauge.messages.GetAllConceptsRequest" do
    end
    add_message "gauge.messages.GetAllConceptsResponse" do
      repeated :concepts, :message, 1, "gauge.messages.ConceptInfo"
    end
    add_message "gauge.messages.ConceptInfo" do
      optional :stepValue, :message, 1, "gauge.messages.ProtoStepValue"
      optional :filepath, :string, 2
      optional :lineNumber, :int32, 3
    end
    add_message "gauge.messages.GetStepValueRequest" do
      optional :stepText, :string, 1
      optional :hasInlineTable, :bool, 2
    end
    add_message "gauge.messages.GetStepValueResponse" do
      optional :stepValue, :message, 1, "gauge.messages.ProtoStepValue"
    end
    add_message "gauge.messages.GetLanguagePluginLibPathRequest" do
      optional :language, :string, 1
    end
    add_message "gauge.messages.GetLanguagePluginLibPathResponse" do
      optional :path, :string, 1
    end
    add_message "gauge.messages.ErrorResponse" do
      optional :error, :string, 1
    end
    add_message "gauge.messages.PerformRefactoringRequest" do
      optional :oldStep, :string, 1
      optional :newStep, :string, 2
    end
    add_message "gauge.messages.PerformRefactoringResponse" do
      optional :success, :bool, 1
      repeated :errors, :string, 2
      repeated :filesChanged, :string, 3
    end
    add_message "gauge.messages.ExtractConceptRequest" do
      optional :conceptName, :message, 1, "gauge.messages.step"
      repeated :steps, :message, 2, "gauge.messages.step"
      optional :changeAcrossProject, :bool, 3
      optional :conceptFileName, :string, 4
      optional :selectedTextInfo, :message, 5, "gauge.messages.textInfo"
    end
    add_message "gauge.messages.textInfo" do
      optional :fileName, :string, 1
      optional :startingLineNo, :int32, 2
      optional :endLineNo, :int32, 3
    end
    add_message "gauge.messages.step" do
      optional :name, :string, 1
      optional :table, :string, 2
      optional :paramTableName, :string, 3
    end
    add_message "gauge.messages.ExtractConceptResponse" do
      optional :isSuccess, :bool, 1
      optional :error, :string, 2
      repeated :filesChanged, :string, 3
    end
    add_message "gauge.messages.FormatSpecsRequest" do
      repeated :specs, :string, 1
    end
    add_message "gauge.messages.FormatSpecsResponse" do
      repeated :errors, :string, 1
      repeated :warnings, :string, 2
    end
    add_message "gauge.messages.UnsupportedApiMessageResponse" do
    end
    add_message "gauge.messages.APIMessage" do
      optional :messageType, :enum, 1, "gauge.messages.APIMessage.APIMessageType"
      optional :messageId, :int64, 2
      optional :projectRootRequest, :message, 3, "gauge.messages.GetProjectRootRequest"
      optional :projectRootResponse, :message, 4, "gauge.messages.GetProjectRootResponse"
      optional :installationRootRequest, :message, 5, "gauge.messages.GetInstallationRootRequest"
      optional :installationRootResponse, :message, 6, "gauge.messages.GetInstallationRootResponse"
      optional :allStepsRequest, :message, 7, "gauge.messages.GetAllStepsRequest"
      optional :allStepsResponse, :message, 8, "gauge.messages.GetAllStepsResponse"
      optional :specsRequest, :message, 9, "gauge.messages.SpecsRequest"
      optional :specsResponse, :message, 10, "gauge.messages.SpecsResponse"
      optional :stepValueRequest, :message, 11, "gauge.messages.GetStepValueRequest"
      optional :stepValueResponse, :message, 12, "gauge.messages.GetStepValueResponse"
      optional :libPathRequest, :message, 13, "gauge.messages.GetLanguagePluginLibPathRequest"
      optional :libPathResponse, :message, 14, "gauge.messages.GetLanguagePluginLibPathResponse"
      optional :error, :message, 15, "gauge.messages.ErrorResponse"
      optional :allConceptsRequest, :message, 16, "gauge.messages.GetAllConceptsRequest"
      optional :allConceptsResponse, :message, 17, "gauge.messages.GetAllConceptsResponse"
      optional :performRefactoringRequest, :message, 18, "gauge.messages.PerformRefactoringRequest"
      optional :performRefactoringResponse, :message, 19, "gauge.messages.PerformRefactoringResponse"
      optional :extractConceptRequest, :message, 20, "gauge.messages.ExtractConceptRequest"
      optional :extractConceptResponse, :message, 21, "gauge.messages.ExtractConceptResponse"
      optional :formatSpecsRequest, :message, 22, "gauge.messages.FormatSpecsRequest"
      optional :formatSpecsResponse, :message, 23, "gauge.messages.FormatSpecsResponse"
      optional :unsupportedApiMessageResponse, :message, 24, "gauge.messages.UnsupportedApiMessageResponse"
    end
    add_enum "gauge.messages.APIMessage.APIMessageType" do
      value :GetProjectRootRequest, 0
      value :GetProjectRootResponse, 1
      value :GetInstallationRootRequest, 2
      value :GetInstallationRootResponse, 3
      value :GetAllStepsRequest, 4
      value :GetAllStepResponse, 5
      value :SpecsRequest, 6
      value :SpecsResponse, 7
      value :GetStepValueRequest, 8
      value :GetStepValueResponse, 9
      value :GetLanguagePluginLibPathRequest, 10
      value :GetLanguagePluginLibPathResponse, 11
      value :ErrorResponse, 12
      value :GetAllConceptsRequest, 13
      value :GetAllConceptsResponse, 14
      value :PerformRefactoringRequest, 15
      value :PerformRefactoringResponse, 16
      value :ExtractConceptRequest, 17
      value :ExtractConceptResponse, 18
      value :FormatSpecsRequest, 19
      value :FormatSpecsResponse, 20
      value :UnsupportedApiMessageResponse, 21
    end
  end
end

module Gauge
  module Messages
    GetProjectRootRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.GetProjectRootRequest").msgclass
    GetProjectRootResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.GetProjectRootResponse").msgclass
    GetInstallationRootRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.GetInstallationRootRequest").msgclass
    GetInstallationRootResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.GetInstallationRootResponse").msgclass
    GetAllStepsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.GetAllStepsRequest").msgclass
    GetAllStepsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.GetAllStepsResponse").msgclass
    SpecsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.SpecsRequest").msgclass
    SpecsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.SpecsResponse").msgclass
    SpecsResponse::SpecDetail = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.SpecsResponse.SpecDetail").msgclass
    GetAllConceptsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.GetAllConceptsRequest").msgclass
    GetAllConceptsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.GetAllConceptsResponse").msgclass
    ConceptInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.ConceptInfo").msgclass
    GetStepValueRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.GetStepValueRequest").msgclass
    GetStepValueResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.GetStepValueResponse").msgclass
    GetLanguagePluginLibPathRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.GetLanguagePluginLibPathRequest").msgclass
    GetLanguagePluginLibPathResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.GetLanguagePluginLibPathResponse").msgclass
    ErrorResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.ErrorResponse").msgclass
    PerformRefactoringRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.PerformRefactoringRequest").msgclass
    PerformRefactoringResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.PerformRefactoringResponse").msgclass
    ExtractConceptRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.ExtractConceptRequest").msgclass
    TextInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.textInfo").msgclass
    Step = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.step").msgclass
    ExtractConceptResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.ExtractConceptResponse").msgclass
    FormatSpecsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.FormatSpecsRequest").msgclass
    FormatSpecsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.FormatSpecsResponse").msgclass
    UnsupportedApiMessageResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.UnsupportedApiMessageResponse").msgclass
    APIMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.APIMessage").msgclass
    APIMessage::APIMessageType = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.APIMessage.APIMessageType").enummodule
  end
end
