#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'messages.pb'; rescue LoadError; end

module Gauge
  module Messages
    # forward declarations
    class Empty < ::ProtocolBuffers::Message; end

    class Empty < ::ProtocolBuffers::Message
      set_fully_qualified_name "gauge.messages.Empty"

    end

    class LspService < ::ProtocolBuffers::Service
      set_fully_qualified_name "gauge.messages.lspService"

      rpc :get_step_names, "GetStepNames", ::Gauge::Messages::StepNameRequest, ::Gauge::Messages::StepNameResponse
      rpc :cache_file, "CacheFile", ::Gauge::Messages::CacheFileRequest, ::Gauge::Messages::Empty
      rpc :get_step_positions, "GetStepPositions", ::Gauge::Messages::StepPositionsRequest, ::Gauge::Messages::StepPositionsResponse
      rpc :get_implementation_files, "GetImplementationFiles", ::Gauge::Messages::Empty, ::Gauge::Messages::ImplementationFileListResponse
      rpc :implement_stub, "ImplementStub", ::Gauge::Messages::StubImplementationCodeRequest, ::Gauge::Messages::FileDiff
    end
  end
end
