# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: lsp.proto for package 'gauge.messages'
# Original file comments:
# Copyright 2015 ThoughtWorks, Inc.
#
# This file is part of gauge-proto.
#
# gauge-proto is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# gauge-proto is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with gauge-proto.  If not, see <http://www.gnu.org/licenses/>.
#

require 'grpc'
require 'lsp_pb'

module Gauge
  module Messages
    module LspService
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'gauge.messages.lspService'

        rpc :GetStepNames, StepNameRequest, StepNameResponse
        rpc :CacheFile, CacheFileRequest, Empty
        rpc :GetStepPositions, StepPositionsRequest, StepPositionsResponse
        rpc :GetImplementationFiles, Empty, ImplementationFileListResponse
        rpc :ImplementStub, StubImplementationCodeRequest, FileDiff
      end

      Stub = Service.rpc_stub_class
    end
  end
end
