# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lsp.proto

require 'google/protobuf'

require 'messages_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gauge.messages.Empty" do
  end
end

module Gauge
  module Messages
    Empty = Google::Protobuf::DescriptorPool.generated_pool.lookup("gauge.messages.Empty").msgclass
  end
end
