#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Gauge
  module Messages
    # forward declarations
    class ProtoSpec < ::ProtocolBuffers::Message; end
    class ProtoItem < ::ProtocolBuffers::Message; end
    class ProtoScenario < ::ProtocolBuffers::Message; end
    class Span < ::ProtocolBuffers::Message; end
    class ProtoTableDrivenScenario < ::ProtocolBuffers::Message; end
    class ProtoStep < ::ProtocolBuffers::Message; end
    class ProtoConcept < ::ProtocolBuffers::Message; end
    class ProtoTags < ::ProtocolBuffers::Message; end
    class Fragment < ::ProtocolBuffers::Message; end
    class Parameter < ::ProtocolBuffers::Message; end
    class ProtoComment < ::ProtocolBuffers::Message; end
    class ProtoTable < ::ProtocolBuffers::Message; end
    class ProtoTableRow < ::ProtocolBuffers::Message; end
    class ProtoStepExecutionResult < ::ProtocolBuffers::Message; end
    class ProtoExecutionResult < ::ProtocolBuffers::Message; end
    class ProtoHookFailure < ::ProtocolBuffers::Message; end
    class ProtoSuiteResult < ::ProtocolBuffers::Message; end
    class ProtoSpecResult < ::ProtocolBuffers::Message; end
    class ProtoStepValue < ::ProtocolBuffers::Message; end

    # enums
    module ExecutionStatus
      include ::ProtocolBuffers::Enum

      set_fully_qualified_name "gauge.messages.ExecutionStatus"

      NOTEXECUTED = 0
      PASSED = 1
      FAILED = 2
      SKIPPED = 3
    end

    class ProtoSpec < ::ProtocolBuffers::Message
      set_fully_qualified_name "gauge.messages.ProtoSpec"

      optional :string, :specHeading, 1
      repeated ::Gauge::Messages::ProtoItem, :items, 2
      optional :bool, :isTableDriven, 3
      optional ::Gauge::Messages::ProtoHookFailure, :preHookFailure, 4
      optional ::Gauge::Messages::ProtoHookFailure, :postHookFailure, 5
      optional :string, :fileName, 6
      repeated :string, :tags, 7
    end

    class ProtoItem < ::ProtocolBuffers::Message
      # forward declarations

      # enums
      module ItemType
        include ::ProtocolBuffers::Enum

        set_fully_qualified_name "gauge.messages.ProtoItem.ItemType"

        Step = 0
        Comment = 1
        Concept = 2
        Scenario = 3
        TableDrivenScenario = 4
        Table = 5
        Tags = 6
      end

      set_fully_qualified_name "gauge.messages.ProtoItem"

      optional ::Gauge::Messages::ProtoItem::ItemType, :itemType, 1
      optional ::Gauge::Messages::ProtoStep, :step, 2
      optional ::Gauge::Messages::ProtoConcept, :concept, 3
      optional ::Gauge::Messages::ProtoScenario, :scenario, 4
      optional ::Gauge::Messages::ProtoTableDrivenScenario, :tableDrivenScenario, 5
      optional ::Gauge::Messages::ProtoComment, :comment, 6
      optional ::Gauge::Messages::ProtoTable, :table, 7
      optional ::Gauge::Messages::ProtoTags, :tags, 8
    end

    class ProtoScenario < ::ProtocolBuffers::Message
      set_fully_qualified_name "gauge.messages.ProtoScenario"

      optional :string, :scenarioHeading, 1
      optional :bool, :failed, 2
      repeated ::Gauge::Messages::ProtoItem, :contexts, 3
      repeated ::Gauge::Messages::ProtoItem, :scenarioItems, 4
      optional ::Gauge::Messages::ProtoHookFailure, :preHookFailure, 5
      optional ::Gauge::Messages::ProtoHookFailure, :postHookFailure, 6
      repeated :string, :tags, 7
      optional :int64, :executionTime, 8
      optional :bool, :skipped, 9
      repeated :string, :skipErrors, 10
      optional :string, :ID, 11
      repeated ::Gauge::Messages::ProtoItem, :tearDownSteps, 12
      optional ::Gauge::Messages::Span, :span, 13
      optional ::Gauge::Messages::ExecutionStatus, :executionStatus, 14
    end

    class Span < ::ProtocolBuffers::Message
      set_fully_qualified_name "gauge.messages.Span"

      optional :int64, :start, 1
      optional :int64, :end, 2
    end

    class ProtoTableDrivenScenario < ::ProtocolBuffers::Message
      set_fully_qualified_name "gauge.messages.ProtoTableDrivenScenario"

      optional ::Gauge::Messages::ProtoScenario, :scenario, 1
      optional :int32, :tableRowIndex, 2
    end

    class ProtoStep < ::ProtocolBuffers::Message
      set_fully_qualified_name "gauge.messages.ProtoStep"

      optional :string, :actualText, 1
      optional :string, :parsedText, 2
      repeated ::Gauge::Messages::Fragment, :fragments, 3
      optional ::Gauge::Messages::ProtoStepExecutionResult, :stepExecutionResult, 4
    end

    class ProtoConcept < ::ProtocolBuffers::Message
      set_fully_qualified_name "gauge.messages.ProtoConcept"

      optional ::Gauge::Messages::ProtoStep, :conceptStep, 1
      repeated ::Gauge::Messages::ProtoItem, :steps, 2
      optional ::Gauge::Messages::ProtoStepExecutionResult, :conceptExecutionResult, 3
    end

    class ProtoTags < ::ProtocolBuffers::Message
      set_fully_qualified_name "gauge.messages.ProtoTags"

      repeated :string, :tags, 1
    end

    class Fragment < ::ProtocolBuffers::Message
      # forward declarations

      # enums
      module FragmentType
        include ::ProtocolBuffers::Enum

        set_fully_qualified_name "gauge.messages.Fragment.FragmentType"

        Text = 0
        Parameter = 1
      end

      set_fully_qualified_name "gauge.messages.Fragment"

      optional ::Gauge::Messages::Fragment::FragmentType, :fragmentType, 1
      optional :string, :text, 2
      optional ::Gauge::Messages::Parameter, :parameter, 3
    end

    class Parameter < ::ProtocolBuffers::Message
      # forward declarations

      # enums
      module ParameterType
        include ::ProtocolBuffers::Enum

        set_fully_qualified_name "gauge.messages.Parameter.ParameterType"

        Static = 0
        Dynamic = 1
        Special_String = 2
        Special_Table = 3
        Table = 4
      end

      set_fully_qualified_name "gauge.messages.Parameter"

      optional ::Gauge::Messages::Parameter::ParameterType, :parameterType, 1
      optional :string, :value, 2
      optional :string, :name, 3
      optional ::Gauge::Messages::ProtoTable, :table, 4
    end

    class ProtoComment < ::ProtocolBuffers::Message
      set_fully_qualified_name "gauge.messages.ProtoComment"

      optional :string, :text, 1
    end

    class ProtoTable < ::ProtocolBuffers::Message
      set_fully_qualified_name "gauge.messages.ProtoTable"

      optional ::Gauge::Messages::ProtoTableRow, :headers, 1
      repeated ::Gauge::Messages::ProtoTableRow, :rows, 2
    end

    class ProtoTableRow < ::ProtocolBuffers::Message
      set_fully_qualified_name "gauge.messages.ProtoTableRow"

      repeated :string, :cells, 1
    end

    class ProtoStepExecutionResult < ::ProtocolBuffers::Message
      set_fully_qualified_name "gauge.messages.ProtoStepExecutionResult"

      optional ::Gauge::Messages::ProtoExecutionResult, :executionResult, 1
      optional ::Gauge::Messages::ProtoHookFailure, :preHookFailure, 2
      optional ::Gauge::Messages::ProtoHookFailure, :postHookFailure, 3
      optional :bool, :skipped, 4
      optional :string, :skippedReason, 5
    end

    class ProtoExecutionResult < ::ProtocolBuffers::Message
      # forward declarations

      # enums
      module ErrorType
        include ::ProtocolBuffers::Enum

        set_fully_qualified_name "gauge.messages.ProtoExecutionResult.ErrorType"

        ASSERTION = 0
        VERIFICATION = 1
      end

      set_fully_qualified_name "gauge.messages.ProtoExecutionResult"

      optional :bool, :failed, 1
      optional :bool, :recoverableError, 2
      optional :string, :errorMessage, 3
      optional :string, :stackTrace, 4
      optional :bytes, :screenShot, 5
      optional :int64, :executionTime, 6
      repeated :string, :message, 7
      optional ::Gauge::Messages::ProtoExecutionResult::ErrorType, :errorType, 8
    end

    class ProtoHookFailure < ::ProtocolBuffers::Message
      set_fully_qualified_name "gauge.messages.ProtoHookFailure"

      optional :string, :stackTrace, 1
      optional :string, :errorMessage, 2
      optional :bytes, :screenShot, 3
    end

    class ProtoSuiteResult < ::ProtocolBuffers::Message
      set_fully_qualified_name "gauge.messages.ProtoSuiteResult"

      repeated ::Gauge::Messages::ProtoSpecResult, :specResults, 1
      optional ::Gauge::Messages::ProtoHookFailure, :preHookFailure, 2
      optional ::Gauge::Messages::ProtoHookFailure, :postHookFailure, 3
      optional :bool, :failed, 4
      optional :int32, :specsFailedCount, 5
      optional :int64, :executionTime, 6
      optional :float, :successRate, 7
      optional :string, :environment, 8
      optional :string, :tags, 9
      optional :string, :projectName, 10
      optional :string, :timestamp, 11
      optional :int32, :specsSkippedCount, 12
    end

    class ProtoSpecResult < ::ProtocolBuffers::Message
      set_fully_qualified_name "gauge.messages.ProtoSpecResult"

      optional ::Gauge::Messages::ProtoSpec, :protoSpec, 1
      optional :int32, :scenarioCount, 2
      optional :int32, :scenarioFailedCount, 3
      optional :bool, :failed, 4
      repeated :int32, :failedDataTableRows, 5
      optional :int64, :executionTime, 6
      optional :bool, :skipped, 7
      optional :int32, :scenarioSkippedCount, 9
      repeated :int32, :skippedDataTableRows, 10
    end

    class ProtoStepValue < ::ProtocolBuffers::Message
      set_fully_qualified_name "gauge.messages.ProtoStepValue"

      optional :string, :stepValue, 1
      optional :string, :parameterizedStepValue, 2
      repeated :string, :parameters, 3
    end

  end
end
